name: Sphinx Document

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies of python
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install dependencies of ubuntu package
      run: |
        sudo apt update
        sudo apt install build-essential npm
    - name: Install npm package
      run: |
        npm i yarn && yarn
    - name: Check text
      run: |
        yarn test
    - name: Build HTML
      run: |
        sphinx-build -W docs build
